### ISSUE TITLE
Feature suggestions: HTTP verb and payload, leverage existing webhooks

### ISSUE THREAD

**Issue by teemutammela** [yn5/webhook-contentful-app#158]
Hello,

Here are few feature suggestions that would be useful additions. These suggestions relate closely to my project [contentful-cloudflare-webhook-purge](https://github.com/teemutammela/contentful-cloudflare-webhook-purge).

- Option to define which HTTP verb (GET, POST, PATCH, DELETE etc.) is used to execute the webhook's HTTP request.
- Option to define a payload for the HTTP request.
- Alternatively to the two options above, instead of managing the webhooks internally in the `webhook-contentful-app`, have the app trigger Contentful's existing webhooks instead. As such, `webhook-contentful-app` has overlapping functionality with Contentful's own webhook management.

If any of the aforementioned functionality is already implemented, please excuse my ignorance. 😄

**Comment by yn5** [comment]
Thanks for your contribution @teemutammela! I've added two simple fields for selecting a HTTP verb and defining a payload: https://github.com/yn5/webhook-contentful-app/pull/177. I'm closing the issue but feel free to reopen it if you feel a need to continue the discussion.
